### ISSUE TITLE
Remove prtinln statements (Optional: Add logger library if you want)

### ISSUE THREAD

**Issue by Suryavel-Virtusa** [Zamiuddin/VirtusaCode#6]
https://github.com/Zamiuddin/VirtusaCode/blob/0af42f063a3cfb5645e30fdd049997e3ca7ab2d1/app/src/main/java/com/app/virtusatest/MainActivity.kt#L55

**Comment by Zamiuddin** [comment]
Used the Log's instead of printing statement for the full app.
